spring:
  servlet: 
    multipart:
       max-file-size: 3MB
       max-request-size: 3MB     
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 701508688266-j635486e3co4vmcnaslctbhad2vb7gf0.apps.googleusercontent.com
            client-secret: EhHYIc9AV2PwJ4sWD9awCroK
            scope:
            - email
            - profile    
          facebook:
            clientId: 138173101865029
            clientSecret: 4f5e11415c5e68b092015562ea984e2d
            scope:
            - email
            - public_profile
    
  mail:
     host: smtp.gmail.com
     port: 587
     username: granferiapem@gmail.com
     password: Granferia_2021
#    host: mail.granferia.online
#    port: 587
#    username: administracion@granferia.online
#    password: Granferia_2021
     properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    enable: false
  datasource: 
    url: jdbc:mysql://localhost:3306/granferia?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root

#    url: jdbc:mysql://mysql.granferia.online/granferia
#    username: granferia
#    password: Granferia_2021
    driver-class-name: com.mysql.cj.jdbc.Driver 

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false


